# 工程配置
server:
  # 设置内嵌tomcat端口
  port: 8080
  servlet:
    # 设置上下文根（访问路径）
    context-path: /jyk-total


# Spring配置
spring:
  application:
    name: jyk-total
  # 连接Mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jyk_total
    username: root
    password: Dwxxls@2024
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      # 上传文件大小设置最大为10MB。默认情况下，Spring Boot允许上传文件的大小为1MB
      max-file-size: 10MB

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.jyk.mapper
  # 设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
  executorType: SIMPLE

