# 工程配置
server:
  # 设置内嵌tomcat端口
  port: 8080
  servlet:
    # 设置上下文根（访问路径）
    context-path: /jyk-total


# Spring配置
spring:
  application:
    name: jyk-total
  # 连接Mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jyk_total
    username: root
    password: Dwxxls@2024
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      # 上传文件大小设置最大为10MB。默认情况下，Spring Boot允许上传文件的大小为1MB
      max-file-size: 10MB

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.jyk.mapper
  # 设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
  executorType: SIMPLE

# RSA加解密配置
rsa:
  public:
    key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCRfxdKBzBl5BD/bHQ6VlRNx/FoM+CYB7y3Oeh2EO4H7xSNoLOKhedVEsueqCzIgtPu2r2lR/HQ9B8elOgbNAC7LliWRNE9jN3YubrIGKzPAuiN1Z54sOtFl6/+bQ6IkeVlzncQCurtkR5WVn88vPIFg5e1GhTIN7RF4ut5nnvf5wIDAQAB
  private:
    key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJF/F0oHMGXkEP9sdDpWVE3H8Wgz4JgHvLc56HYQ7gfvFI2gs4qF51USy56oLMiC0+7avaVH8dD0Hx6U6Bs0ALsuWJZE0T2M3di5usgYrM8C6I3Vnniw60WXr/5tDoiR5WXOdxAK6u2RHlZWfzy88gWDl7UaFMg3tEXi63mee9/nAgMBAAECgYBHzJTclkGe9nYg5g9RPorpu1J5HqilvaO2M6Bwqxgb2DKnVXdkU4H+LIFJMSqwZEdbppxRtPgzKlU1DTyhN/9noJ1il4q55GbPw5H7PEQZrelaRLcML0nx80E3x9iX/DHicdpQJ0vrEbuWaXwcGUoUCb/Wp+IrrqoNlxUaVYzDeQJBAM7mfZS7AOYtjbbI+0rwob6+fmX9Y5kxqsTim48tWxOsXOHO0o7wfCBUzagFyxQRjkWerNX3YXcA7P9hKmAEn80CQQC0BjhoC0Uy8sh8wq4AfM/+/0JLJsM+AQqndnjbGy1QCz7lOe+AncWQHLfj0FZdBQ6nawnFsgVoSvQhJGyG2IKDAkBNzrRPaHwQE/WFVdPa/N924iCark30YI8995JUp9PmdB2B9cuNYbbsWbf1hig25dtBJ0kMNjn7DOgTqjDLZzHJAkEAl5lpZMyg4G+tP8rdptF0gsNIe2rQHeXYp/9PdQvk07Q0qepo8wFpvptAjBsEr16z4W51E0N/5DzCayp2LfQjqwJAZ9gLoFp9K4R7/jQepxjiem1RIli1XqFGjHD7I2O205uiQYGZIsReu2BpLVdN/MBQtRVnvAtkQHsybWcjluRgnA==

