CREATE TABLE IF NOT EXISTS `user` (
		id INT AUTO_INCREMENT PRIMARY KEY,
		`name` VARCHAR ( 50 ) NOT NULL,
		age INT,
		email VARCHAR ( 100 ),
		create_by VARCHAR ( 50 ) NOT NULL,
		create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		update_by VARCHAR ( 50 ) NOT NULL,
		update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;